/**
 * File templates for newly created game projects. GenieEngine scaffolds a
 * minimal-but-runnable Godot 4 project so the Run button works immediately
 * and the AI assistant has a valid starting point to build on.
 */

/**
 * Project names are interpolated into Godot config strings, GDScript string
 * literals and Markdown. In those contexts `"` delimits the string, `\` is
 * an escape character, and a raw newline breaks out of the value entirely —
 * e.g. a name containing "\n[autoload]\n…" would inject a config section
 * into project.godot that executes arbitrary GDScript when the project runs.
 * Names are display-only, so strip the dangerous characters rather than
 * trying to escape them per-context.
 */
function sanitize(name: string): string {
  return (
    name
      .replace(/[\\\u0000-\u001f\u007f]/g, ' ')
      .replace(/"/g, "'")
      .replace(/\s+/g, ' ')
      .trim() || 'Untitled Game'
  )
}

export function projectGodot(name: string): string {
  return `; Engine configuration file.
; Generated by GenieEngine — edits are welcome, Godot also rewrites this file.
config_version=5

[application]

; No engine splash — the game boots straight into its first scene on black.
boot_splash/bg_color=Color(0, 0, 0, 1)
boot_splash/show_image=false
config/name="${sanitize(name)}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.7")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1152
window/size/viewport_height=648
; canvas_items stretch keeps the game readable at any size — important for
; GenieEngine's embedded game view, which can be resized freely.
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
; Required for macOS/mobile exports (arm64 needs ETC2/ASTC texture import).
textures/vram_compression/import_etc2_astc=true
`
}

export function mainTscn(name: string): string {
  return `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="Title" type="Label" parent="."]
offset_left = 40.0
offset_top = 40.0
offset_right = 800.0
offset_bottom = 90.0
text = "${sanitize(name)} — built with GenieEngine. Ask the assistant to make a game!"
`
}

export function mainGd(name: string): string {
  // GDScript uses tab indentation by convention (Godot's default).
  // The genieengine header block matches the format mandated in
  // resources/agent-instructions.md — the scaffold must itself comply so the
  // AI sees a live example (and so a future UI parser finds a header in every
  // file, including this one).
  return [
    '#=== genieengine ===',
    '# kind: other',
    '# name: Main',
    '# summary: Entry scene script — instantiates entities and hosts the systems.',
    '# uses: none',
    '#=== /genieengine ===',
    'extends Node2D',
    '',
    '',
    'func _ready() -> void:',
    `\tprint("${sanitize(name)} is running — built with GenieEngine")`,
    ''
  ].join('\n')
}

export function iconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="28" fill="#7c5cff"/><path d="M52 40l34 24-34 24z" fill="#fff"/></svg>
`
}

export function gitignore(): string {
  return `# Godot 4 cache/imported data
.godot/
.DS_Store

# GenieEngine run helpers (auto-generated while the game runs, removed on stop)
override.cfg
genieengine_test_agent.gd

# GenieEngine export output
exports/

# GenieEngine local state (chat history, attachments, test screenshots)
.genieengine/
`
}

/**
 * AGENTS.md is picked up automatically by OpenCode (and other coding agents),
 * but it is a snapshot frozen into each project at creation time — so it
 * stays THIN and project-owned. The app's actual build rules (scope, ECS
 * architecture, asset layout, file headers, testing) live in
 * resources/agent-instructions.md and are injected into every app-spawned
 * chat server via the `instructions` config (see opencode-config.ts), which
 * keeps them versioned with the app instead of going stale per project.
 *
 * If you change this template's output, add the outgoing version's body hash
 * to APP_OWNED_AGENTS_BODY_HASHES in projects.ts — that list is how existing
 * projects' unedited AGENTS.md files get upgraded on open.
 */
export function agentsMd(name: string): string {
  return `# ${sanitize(name)}

This is a **Godot 4** game project created with **GenieEngine**, an AI-powered game engine.

GenieEngine gives the assistant its full build rules (scope, ECS architecture, asset
layout, file headers, testing tools) automatically while the app runs — those rules are
versioned with the app rather than stored here.

Use this file for project-specific notes the assistant should always know: game design
decisions, art direction, conventions, TODOs.
`
}
