import { existsSync } from 'node:fs'
import { rename, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * The GDScript autoload injected into a project for every embedded run —
 * user play and AI test runs alike. Over the existing debugger channel it:
 *
 *  - answers probe commands (EngineDebugger message capture "ogtest"),
 *    letting the assistant observe a game running off-screen:
 *      ogtest:screenshot [id, path]  → renders a frame and saves a PNG
 *      ogtest:eval       [id, expr]  → evaluates a GDScript Expression against
 *                                      the scene tree root, returns the result
 *      ogtest:tree       [id]        → dumps the scene tree (paths + classes)
 *      ogtest:input      [id, json]  → injects an InputEvent in-process (used
 *                                      on platforms without the embedded
 *                                      display server, where embed:event has
 *                                      no receiver — see godot-input-codec.ts)
 *      ogtest:quit       [id]        → quits the game cleanly (windowed runs
 *                                      can't be closed via embed:win_event)
 *    Every command answers with `ogtest:done` [id, ok, text].
 *  - streams frame timings for the editor's FPS counter and the perf log
 *    (see perf-monitor.ts): `ogperf:frames` [PackedFloat32Array of frame
 *    deltas], sent about once per second.
 *
 * Injection uses override.cfg (Godot merges it over project.godot; the user's
 * file is never touched) and both files are removed when the run stops.
 */

export const TEST_AGENT_SCRIPT_NAME = 'genieengine_test_agent.gd'
const OVERRIDE_CFG_NAME = 'override.cfg'
const OVERRIDE_BACKUP_NAME = 'override.cfg.genieengine-bak'

// GDScript uses tab indentation (Godot requires consistency).
const TEST_AGENT_SCRIPT = `# Auto-generated by GenieEngine while the game runs. Removed when the run stops —
# safe to delete, do not edit or commit.
extends Node

var _queue: Array = []
var _perf_deltas: PackedFloat32Array = PackedFloat32Array()
var _perf_accum := 0.0

func _ready() -> void:
	# Keep probing and frame reporting alive while the game is paused.
	process_mode = Node.PROCESS_MODE_ALWAYS
	if EngineDebugger.is_active():
		EngineDebugger.register_message_capture("ogtest", _on_message)

func _exit_tree() -> void:
	# Unregister explicitly — leaving it to engine teardown prints a spurious
	# "Capture not registered: 'ogtest'" error in the game's output on quit.
	if EngineDebugger.is_active() and EngineDebugger.has_capture("ogtest"):
		EngineDebugger.unregister_message_capture("ogtest")

func _on_message(message: String, data: Array) -> bool:
	# Queue instead of handling inline: capture callbacks can't await, and
	# screenshots must wait for a rendered frame.
	_queue.append([message, data])
	return true

func _process(delta: float) -> void:
	while _queue.size() > 0:
		var item: Array = _queue.pop_front()
		_dispatch(item[0], item[1])
	# Frame timing stream for GenieEngine's FPS counter and perf log: batch this
	# second's frame deltas into one debugger message (~1/s, a few KB).
	_perf_deltas.append(delta)
	_perf_accum += delta
	if _perf_accum >= 1.0:
		if EngineDebugger.is_active():
			EngineDebugger.send_message("ogperf:frames", [_perf_deltas])
		_perf_deltas = PackedFloat32Array()
		_perf_accum = 0.0

func _dispatch(cmd: String, data: Array) -> void:
	var id: int = int(data[0]) if data.size() > 0 else -1
	match cmd:
		"screenshot":
			_do_screenshot(id, str(data[1]))
		"eval":
			_do_eval(id, str(data[1]))
		"tree":
			_do_tree(id)
		"input":
			_do_input(id, str(data[1]))
		"quit":
			get_tree().quit()
		_:
			_reply(id, false, "unknown test command: %s" % cmd)

func _reply(id: int, ok: bool, text: String) -> void:
	EngineDebugger.send_message("ogtest:done", [id, ok, text])

func _do_screenshot(id: int, path: String) -> void:
	await RenderingServer.frame_post_draw
	var img := get_viewport().get_texture().get_image()
	if img == null or img.is_empty():
		_reply(id, false, "viewport produced no image")
		return
	var err := img.save_png(path)
	if err == OK:
		_reply(id, true, path)
	else:
		_reply(id, false, "save_png failed with error %d" % err)

func _do_eval(id: int, code: String) -> void:
	var expr := Expression.new()
	var err := expr.parse(code, [])
	if err != OK:
		_reply(id, false, "parse error: %s" % expr.get_error_text())
		return
	var result = expr.execute([], get_tree().root, true)
	if expr.has_execute_failed():
		_reply(id, false, "execute failed: %s" % expr.get_error_text())
		return
	var text := JSON.stringify(result)
	if text == "" or text == "null" and result != null:
		text = str(result)
	_reply(id, true, text)

# Rebuild an InputEvent from the JSON payload built by godot-input-codec.ts
# (*ToAgentPayload) and inject it as if it came from the OS. Positions are in
# window coordinates, same as real events.
func _do_input(id: int, json: String) -> void:
	var d = JSON.parse_string(json)
	if typeof(d) != TYPE_DICTIONARY:
		_reply(id, false, "invalid input payload")
		return
	var ev: InputEvent = null
	match str(d.get("kind", "")):
		"key":
			var k := InputEventKey.new()
			k.keycode = int(d.get("keycode", 0))
			k.physical_keycode = int(d.get("physical", 0))
			k.key_label = k.keycode
			k.unicode = int(d.get("unicode", 0))
			k.pressed = bool(d.get("pressed", false))
			k.echo = bool(d.get("echo", false))
			ev = k
		"mouse_button":
			var b := InputEventMouseButton.new()
			b.position = Vector2(float(d.get("x", 0)), float(d.get("y", 0)))
			b.global_position = b.position
			b.button_index = int(d.get("button", 1))
			b.button_mask = int(d.get("mask", 0))
			b.pressed = bool(d.get("pressed", false))
			b.double_click = bool(d.get("double", false))
			ev = b
		"mouse_motion":
			var m := InputEventMouseMotion.new()
			m.position = Vector2(float(d.get("x", 0)), float(d.get("y", 0)))
			m.global_position = m.position
			m.relative = Vector2(float(d.get("rx", 0)), float(d.get("ry", 0)))
			m.button_mask = int(d.get("mask", 0))
			ev = m
		_:
			_reply(id, false, "unknown input kind")
			return
	var wm := ev as InputEventWithModifiers
	if wm:
		wm.shift_pressed = bool(d.get("shift", false))
		wm.ctrl_pressed = bool(d.get("ctrl", false))
		wm.alt_pressed = bool(d.get("alt", false))
		wm.meta_pressed = bool(d.get("meta", false))
	Input.parse_input_event(ev)
	_reply(id, true, "ok")

func _do_tree(id: int) -> void:
	var lines: PackedStringArray = []
	var scene := get_tree().current_scene
	if scene == null:
		_reply(id, false, "no current scene")
		return
	_walk(scene, 0, lines)
	_reply(id, true, "\\n".join(lines))

func _walk(node: Node, depth: int, lines: PackedStringArray) -> void:
	if lines.size() >= 400 or depth > 12:
		return
	lines.append("%s%s (%s)" % ["  ".repeat(depth), node.name, node.get_class()])
	for child in node.get_children():
		_walk(child, depth + 1, lines)
`

/** Godot merges override.cfg over project.godot at startup. */
const OVERRIDE_CFG = `; Auto-generated by GenieEngine while the game runs. Removed when the run stops —
; safe to delete, do not commit.

[autoload]

GenieEngineTestAgent="*res://${TEST_AGENT_SCRIPT_NAME}"
`

export async function injectTestAgent(projectPath: string): Promise<void> {
  const overridePath = join(projectPath, OVERRIDE_CFG_NAME)
  if (existsSync(overridePath)) {
    await rename(overridePath, join(projectPath, OVERRIDE_BACKUP_NAME))
  }
  await writeFile(join(projectPath, TEST_AGENT_SCRIPT_NAME), TEST_AGENT_SCRIPT)
  await writeFile(overridePath, OVERRIDE_CFG)
}

/** Remove injected files; restore the user's own override.cfg if backed up. */
export async function cleanupTestAgent(projectPath: string): Promise<void> {
  await rm(join(projectPath, TEST_AGENT_SCRIPT_NAME), { force: true })
  await rm(join(projectPath, OVERRIDE_CFG_NAME), { force: true })
  const backup = join(projectPath, OVERRIDE_BACKUP_NAME)
  if (existsSync(backup)) {
    await rename(backup, join(projectPath, OVERRIDE_CFG_NAME))
  }
}
